### ISSUE TITLE
把 crash.cli 显式地加到依赖里

### ISSUE THREAD

**Issue by hengyunabc** [hengyunabc/xdiamond#11]
有些用户在编绎时，不能通过。发现是 crash.cli 并没有引入。可能是某些maven仓库同步出错了。

``` xml
<dependency>
    <groupId>org.crashub</groupId>
    <artifactId>crash.cli</artifactId>
    <version>1.3.1</version>
</dependency>
```

在官方的maven仓库里是通过`crash.embed.spring`直接引入了的。

``` xml
        <dependency>
            <groupId>org.crashub</groupId>
            <artifactId>crash.embed.spring</artifactId>
            <version>1.3.1</version>
```

**Comment by hengyunabc** [comment]
实际测试了 oschina 的maven仓库，发现编绎了很多次都没有成功。

**所以建议在编绎XDiamond时不要使用国内的maven仓库，尽量只使用官方的仓库。**

可以把 `~/.m2/settings.xml` 文件备份之后，再删除掉。这样子默认使用的就是官方的仓库。

**下面这个是oschina的maven仓库，建议不要使用！！，如果发现settings.xml有相关的配置，请删除掉！**

``` xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
  <mirrors>
    <mirror>
      <id>CN</id>
      <name>OSChina Central</name>
      <url>http://maven.oschina.net/content/groups/public/</url>
      <mirrorOf>central</mirrorOf>
    </mirror>
  </mirrors>
</settings>
```

**Comment by hengyunabc** [comment]
经过测试，发现是windows下面的mvn的bug。

正确的依赖关系是：
- crash.embed.spring 引入了 crash.shell
- crash.shell 引入了 crash.cli

https://repo1.maven.org/maven2/org/crashub/crash.embed.spring/1.3.1/crash.embed.spring-1.3.1.pom

https://repo1.maven.org/maven2/org/crashub/crash.shell/1.3.1/crash.shell-1.3.1.pom

但是可能因为在 `crash.embed.spring-1.3.1.pom` 里引入了两个`crash.shell`，所以导致了在windows下面解析依赖时出错了。

``` xml
<!--  Core dependencies  -->
<dependency>
<groupId>org.crashub</groupId>
<artifactId>crash.shell</artifactId>
</dependency>

<dependency>
<groupId>org.crashub</groupId>
<artifactId>crash.shell</artifactId>
<type>test-jar</type>
<scope>test</scope>
</dependency>
```

**Comment by hengyunabc** [comment]
另外，在windows jdk7下面编绎会报错：

```
[ERROR] Exit code: 1 - javadoc: 错误 - 无效的标记: -Xdoclint:none
```

可以加上参数：

```
mvn clean install -DskipTests -Dmaven.javadoc.skip
```

后面需要在主pom.xml里把生成javadoc移到release这个profile里。这样子install就不会生成javadoc了。

**Comment by FangOba** [comment]
@hengyunabc 我们公司内网也是有问题的，不过windows mvn的bug的话，升级mvn会有问题吗？

**Comment by hengyunabc** [comment]
@Xiaobaxi  最新版本的windows 的mvn 3.3.9 也有问题。

解决办法就是临时在xdiamond-server/pom.xml里加入 crash.cli 的依赖。
