### ISSUE TITLE
关于用户权限的问题

### ISSUE THREAD

**Issue by yangqubu** [hengyunabc/xdiamond#16]
增加用户的时候，为什么会增加一个用户组？

删除用户组的时候，数据库数据删除的不够干净。关联数据无法删除

**Comment by hengyunabc** [comment]
这个是参考gitlab做的权限设计，每一个用户都有一个group。 

的确有可能关联数据没有删除干净。因为从效率角度考虑，数据库的表都是没有做关联的。

**Comment by yangqubu** [comment]
发现有一个问题，如果我删除一个组（组中有一个成员），该成员用户只有一个组（已被删除）,这个时候用该成员账户登录，会出现bug。（空指针问题，甚至在短时间内（session有效期内）页面一直无法展示）。

**Comment by hengyunabc** [comment]
默认的约束就是一个用户肯定要有一个组，最差的情况下也有一个名字和他自身名字一样的组。

在做用户删除时，的确没有做很多的工作来保证正确性。管理员在做删除时应当比较小心操作。

后面有比较多时间时才会考虑完善这些细节。
