### ISSUE TITLE
编译不过----org.crsh.cli.impl不存在

### ISSUE THREAD

**Issue by helloworldtang** [hengyunabc/xdiamond#18]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project xdiamond-server: Compilation failure: Compilation failure:
[ERROR] xdiamond/xdiamond-server/src/main/java/io/github/xdiamond/web/crash/CRaSHConnector.java:[35,25] 程序包org.crsh.cli.impl不存在
[ERROR] xdiamond/xdiamond-server/src/main/java/io/github/xdiamond/web/crash/CRaSHConnector.java:[36,36] 程序包org.crsh.cli.impl.completion不存在
[ERROR] xdiamond/xdiamond-server/src/main/java/io/github/xdiamond/web/crash/CRaSHConnector.java:[37,24] 程序包org.crsh.cli.spi不存在
[ERROR] xdiamond/xdiamond-server/src/main/java/io/github/xdiamond/web/crash/CRaSHConnector.java:[198,13] 找不到符号
[ERROR] 符号:   类 CompletionMatch
[ERROR] 位置: 类 io.github.xdiamond.web.crash.CRaSHConnector
[ERROR] xdiamond/xdiamond-server/src/main/java/io/github/xdiamond/web/crash/CRaSHConnector.java:[199,13] 找不到符号
[ERROR] 符号:   类 Completion
[ERROR] 位置: 类 io.github.xdiamond.web.crash.CRaSHConnector
[ERROR] xdiamond/xdiamond-server/src/main/java/io/github/xdiamond/web/crash/CRaSHConnector.java:[200,13] 找不到符号
[ERROR] 符号:   类 Delimiter
[ERROR] 位置: 类 io.github.xdiamond.web.crash.CRaSHConnector
[ERROR] -> [Help 1]

**Comment by hengyunabc** [comment]
看 #11 ，下次发新版时会带上。
