### ISSUE TITLE
启动xdiamond-server遇到问题

### ISSUE THREAD

**Issue by carywh** [hengyunabc/xdiamond#21]
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'metricRegistry' is defined

**Comment by hengyunabc** [comment]
前面有没有其它的错误信息？

**Comment by carywh** [comment]
主要就是这个错误引起的，用jetty会有这种错误，后来用tomcat7 maven插件启动ok

**Comment by hengyunabc** [comment]
我测试了下 ，启动没有问题。

```
cd xidamond-server
mvn jetty:run -DskipTests
```

可以试下先在项目的根目录 `mvn clean install -DskipTests`。
