### ISSUE TITLE
使用客户端高级配置bSyncToSystemProperties没有生效

### ISSUE THREAD

**Issue by wuqqq** [hengyunabc/xdiamond#22]
试了一下客户端高级配置：bSyncToSystemProperties，发现源码中对于这个属性是这样解析的：
`if (!StringUtils.isEmpty(bSyncToSystemProperties)) {
      bSyncToSystemProperties = helper.replacePlaceholders(bSyncToSystemProperties, properties);
      xDiamondConfig.setbSyncToSystemProperties(Boolean.getBoolean(bSyncToSystemProperties));
    }`
在spring中这样配置：
`<bean id="xDiamondConfig" class="io.github.xdiamond.client.spring.XDiamondConfigFactoryBean">
                ...
        <property name="bSyncToSystemProperties" value="true" />
    </bean>`
这样写属性注入失败（实际并没有拿到true，而是null），Boolean.getBoolean(name)方法是从环境变量中获取value，而实际是直接注入了值"true"，这里似乎应该改为Boolean.valueOf()，是我使用有误还是？
不过还是要说，xdiamond很好很强大 :)

**Comment by hengyunabc** [comment]
😂   的确这里搞错了。下次发布修复。

**Comment by FangOba** [comment]
@wuqqq 提交一个pull request也不错啊

**Comment by FangOba** [comment]
@hengyunabc 我们在使用xdiamond，并且也做了一些改造，看看到时候能否提些pull给你。@wuqqq

**Comment by hengyunabc** [comment]
@Xiaobaxi  可以的，非常欢迎提交 pull request.

**Comment by zengan** [comment]
xDiamondConfig.setbPrintConfigWhenBoot(Boolean.getBoolean(bPrintConfigWhenBoot));
这个API使用错误，设置为true也是返回false
