### ISSUE TITLE
断开重连问题

### ISSUE THREAD

**Issue by Simonfld** [hengyunabc/xdiamond#27]
`
void channelUnregistered(final ChannelHandlerContext ctx) {
    currentRetryTimes++;
    if (currentRetryTimes > maxRetryTimes) {
      return;
    }

    int currentRetryInterval = retryIntervalSeconds;
    if (bBackOffRetryInterval) {
      // 注意currentRetryInterval 可能会溢出
      currentRetryInterval = retryIntervalSeconds * (currentRetryTimes >= 30 ? 1 << 30 : 1 << currentRetryTimes);
      if (currentRetryInterval <= 0) {
        currentRetryInterval = maxRetryIntervalSeconds;
      }
    }
    if (currentRetryInterval > maxRetryIntervalSeconds) {
      currentRetryInterval = maxRetryIntervalSeconds;
    }
    logger.info("Waiting for " + currentRetryInterval + "s to reconnect");

    final EventLoop loop = ctx.channel().eventLoop();
    loop.schedule(new Runnable() {
      @Override
      public void run() {
        logger.info("Reconnecting to {}:{}", serverAddress, port);
        configureBootstrap(new Bootstrap(), loop).connect().addListener(new FutureListener<Void>() {
          @Override
          public void operationComplete(Future<Void> future) throws Exception {
            if (!future.isSuccess()) {
              logger.error("can not connection to {}:{}", serverAddress, port, future.cause());
            } else {
              logger.info("connection to {}:{} success.", serverAddress, port);
            }
          }
        });
      }
    }, currentRetryInterval, TimeUnit.SECONDS);
  }
`

这里首次断开后，只会重连一次吗？  如果这次也连不上，后面就不做任何处理了。。。

**Comment by Simonfld** [comment]
是不是加个定时重连要更好点？

**Comment by hengyunabc** [comment]
为什么说是只重连一次？这里会重试多次。

**Comment by Simonfld** [comment]
嗯，看错了，每次连接都会触发channelregister, channelunregister
